[config]
version_check = false

[templates.waybar]
input_path = '~/.config/matugen/colors.css'
output_path = '~/.config/waybar/matugen_colors.css'

[templates.hyprland]
input_path = '~/.config/matugen/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
