[config]
version_check = false

[templates.waybar]
input_path = '~/.config/matugen/colors.css'
output_path = '~/.config/waybar/css/matugen_colors.css'

[templates.hyprland]
input_path = '~/.config/matugen/hyprland-colors.conf'
output_path = '~/.config/hypr/matugen_colors.conf'

[templates.fuzzel]
input_path = '~/.config/matugen/colors.ini'
output_path = '~/.config/fuzzel/colors.ini'
